# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund
COPY . .
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN=ai-text-to-audio-ebe97.firebaseapp.com
ARG VITE_FIREBASE_DATABASE_URL=https://ai-text-to-audio-ebe97-default-rtdb.firebaseio.com
ARG VITE_FIREBASE_PROJECT_ID=ai-text-to-audio-ebe97
ARG VITE_FIREBASE_STORAGE_BUCKET=ai-text-to-audio-ebe97.firebasestorage.app
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_DEFAULT_VOICE_ID=b2cf0387ecb446d78a77d23284413f51
ARG VITE_TTS_MODEL=fish-audio/s2.1-pro-free:free
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_DATABASE_URL=$VITE_FIREBASE_DATABASE_URL \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_DEFAULT_VOICE_ID=$VITE_DEFAULT_VOICE_ID \
    VITE_TTS_MODEL=$VITE_TTS_MODEL
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
